### ISSUE TITLE
Heroku Button Deploy - Twitter Login Broken

### ISSUE THREAD

**Issue by brianjking** [upvote/upvote#13]
![Twitter Login Broken](http://i.imgur.com/yjpcJRM.png)

Twitter login seems to be broken in the Heroku 1 button deploy... http://imgur.com/yjpcJRM

**Comment by chrisb** [comment]
@brianjking recently updated the `app.json` with some additional variables you need (twitter app ID/secret key) here: https://github.com/upvote/upvote/commit/acea58fc6c385141bedd2a1687f9a896d536a4d1

Can you give it another try?
